skip instance stuff in circle config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -131,115 +131,122 @@ jobs:
           name: Download Configuration
           when: always
           command: |
-            if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
-              echo "Skipping instance tests for forked PRs"
-              exit 0
-            fi
-            if ./Tests/scripts/is_ami.sh ;
-              then
-                ./Tests/scripts/download_demisto_conf.sh
-              else
-                ./Tests/lastest_server_build_scripts/download_demisto_conf.sh
-            fi
+            # if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
+            #   echo "Skipping instance tests for forked PRs"
+            #   exit 0
+            # fi
+            # if ./Tests/scripts/is_ami.sh ;
+            #   then
+            #     ./Tests/scripts/download_demisto_conf.sh
+            #   else
+            #     ./Tests/lastest_server_build_scripts/download_demisto_conf.sh
+            # fi
+            exit 0
       - run:
           name: Create Instance
           when: always
           command: |
-            if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
-              echo "Skipping instance tests for forked PRs"
-              exit 0
-            fi
-            if ./Tests/scripts/is_ami.sh ;
-              then
-                if [ -n "${NIGHTLY}" ] ;
-                  then
-                    export IFRA_ENV_TYPE=Content-Master
-                  else
-                    export IFRA_ENV_TYPE=Content-Env
-                fi
-                python ./Tests/scripts/awsinstancetool/aws_instance_tool.py -envType $IFRA_ENV_TYPE -outfile ./env_results.json
-              else
-                python ./Tests/scripts/awsinstancetool/aws_instance_tool.py -envType CustomBuild -outfile ./env_results.json
-            fi
+            # if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
+            #   echo "Skipping instance tests for forked PRs"
+            #   exit 0
+            # fi
+            # if ./Tests/scripts/is_ami.sh ;
+            #   then
+            #     if [ -n "${NIGHTLY}" ] ;
+            #       then
+            #         export IFRA_ENV_TYPE=Content-Master
+            #       else
+            #         export IFRA_ENV_TYPE=Content-Env
+            #     fi
+            #     python ./Tests/scripts/awsinstancetool/aws_instance_tool.py -envType $IFRA_ENV_TYPE -outfile ./env_results.json
+            #   else
+            #     python ./Tests/scripts/awsinstancetool/aws_instance_tool.py -envType CustomBuild -outfile ./env_results.json
+            # fi
+            exit 0
       - run:
           name: Setup Instance
           when: always
           command: |
-            if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
-              echo "Skipping instance tests for forked PRs"
-              exit 0
-            fi
-            if ./Tests/scripts/is_ami.sh ;
-              then
-                python ./Tests/scripts/run_content_installation.py
-                python ./Tests/scripts/wait_until_server_ready.py -c $(cat secret_conf_path) -v $CONTENT_VERSION
-              else
-                ./Tests/lastest_server_build_scripts/run_installer_on_instance.sh
-                python ./Tests/scripts/wait_until_server_ready.py -c $(cat secret_conf_path) -v $CONTENT_VERSION --non-ami
-            fi
+            # if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
+            #   echo "Skipping instance tests for forked PRs"
+            #   exit 0
+            # fi
+            # if ./Tests/scripts/is_ami.sh ;
+            #   then
+            #     python ./Tests/scripts/run_content_installation.py
+            #     python ./Tests/scripts/wait_until_server_ready.py -c $(cat secret_conf_path) -v $CONTENT_VERSION
+            #   else
+            #     ./Tests/lastest_server_build_scripts/run_installer_on_instance.sh
+            #     python ./Tests/scripts/wait_until_server_ready.py -c $(cat secret_conf_path) -v $CONTENT_VERSION --non-ami
+            # fi
+            exit 0
       - run:
           name: Run Tests - Latest GA
           shell: /bin/bash
           when: always
           command: |
-            if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
-              echo "Skipping instance tests for forked PRs"
-              exit 0
-            fi
-            if ./Tests/scripts/is_ami.sh ;
-              then
-                ./Tests/scripts/run_tests.sh "Demisto GA"
-              else
-                ./Tests/lastest_server_build_scripts/run_tests.sh
-            fi
+            # if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
+            #   echo "Skipping instance tests for forked PRs"
+            #   exit 0
+            # fi
+            # if ./Tests/scripts/is_ami.sh ;
+            #   then
+            #     ./Tests/scripts/run_tests.sh "Demisto GA"
+            #   else
+            #     ./Tests/lastest_server_build_scripts/run_tests.sh
+            # fi
+            exit 0
       - run:
           name: Run Tests - One Before GA
           shell: /bin/bash
           when: always
           command: |
-            if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
-              echo "Skipping instance tests for forked PRs"
-              exit 0
-            fi
-            if ./Tests/scripts/is_ami.sh ;
-              then
-                ./Tests/scripts/run_tests.sh "Demisto one before GA"
-              else
-                echo "Not AMI run, can't run on this version"
-            fi
+            # if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
+            #   echo "Skipping instance tests for forked PRs"
+            #   exit 0
+            # fi
+            # if ./Tests/scripts/is_ami.sh ;
+            #   then
+            #     ./Tests/scripts/run_tests.sh "Demisto one before GA"
+            #   else
+            #     echo "Not AMI run, can't run on this version"
+            # fi
+            exit 0
       - run:
           name: Run Tests - Two Before GA
           shell: /bin/bash
           when: always
           command: |
-            if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
-              echo "Skipping instance tests for forked PRs"
-              exit 0
-            fi
-            if ./Tests/scripts/is_ami.sh ;
-              then
-                ./Tests/scripts/run_tests.sh "Demisto two before GA"
-              else
-                echo "Not AMI run, can't run on this version"
-            fi
+            # if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
+            #   echo "Skipping instance tests for forked PRs"
+            #   exit 0
+            # fi
+            # if ./Tests/scripts/is_ami.sh ;
+            #   then
+            #     ./Tests/scripts/run_tests.sh "Demisto two before GA"
+            #   else
+            #     echo "Not AMI run, can't run on this version"
+            # fi
+            exit 0
       - run:
           name: Run Tests - Server Master
           shell: /bin/bash
           when: always
           command: |
-            if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
-              echo "Skipping instance tests for forked PRs"
-              exit 0
-            fi
-            if ./Tests/scripts/is_ami.sh ;
-              then
-                ./Tests/scripts/run_tests.sh "Server Master"
-                export RETVAL=$?
-                cp ./Tests/failed_tests.txt $CIRCLE_ARTIFACTS/failed_tests.txt
-                exit $RETVAL
-            else
-                echo "Not AMI run, can't run on this version"
-            fi
+            # if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
+            #   echo "Skipping instance tests for forked PRs"
+            #   exit 0
+            # fi
+            # if ./Tests/scripts/is_ami.sh ;
+            #   then
+            #     ./Tests/scripts/run_tests.sh "Server Master"
+            #     export RETVAL=$?
+            #     cp ./Tests/failed_tests.txt $CIRCLE_ARTIFACTS/failed_tests.txt
+            #     exit $RETVAL
+            # else
+            #     echo "Not AMI run, can't run on this version"
+            # fi
+            exit 0
       - store_artifacts:
           path: artifacts
           destination: artifacts
@@ -262,23 +269,25 @@ jobs:
       - run:
           name: Instance Test
           command: |
-            if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
-              echo "Skipping instance tests for forked PRs"
-              exit 0
-            fi
-            ./Tests/scripts/instance_test.sh
+            # if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
+            #   echo "Skipping instance tests for forked PRs"
+            #   exit 0
+            # fi
+            # ./Tests/scripts/instance_test.sh
+            exit 0
           when: always
       - run:
           name: Destroy Instances
           command: |
-            if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
-              echo "Skipping instance tests for forked PRs"
-              exit 0
-            fi
-            python ./Tests/scripts/destroy_instances.py $CIRCLE_ARTIFACTS ./env_results.json
-            export PSWD=$(jq .serverLogsZipPassword < $(cat secret_conf_path) | cut -d \" -f 2)
-            zip -P $PSWD $CIRCLE_ARTIFACTS/ServerLogs.zip $CIRCLE_ARTIFACTS/server*.log
-            rm -f $CIRCLE_ARTIFACTS/server*.log
+            # if [[ $CIRCLE_BRANCH =~ pull/[0-9]+ ]]; then
+            #   echo "Skipping instance tests for forked PRs"
+            #   exit 0
+            # fi
+            # python ./Tests/scripts/destroy_instances.py $CIRCLE_ARTIFACTS ./env_results.json
+            # export PSWD=$(jq .serverLogsZipPassword < $(cat secret_conf_path) | cut -d \" -f 2)
+            # zip -P $PSWD $CIRCLE_ARTIFACTS/ServerLogs.zip $CIRCLE_ARTIFACTS/server*.log
+            # rm -f $CIRCLE_ARTIFACTS/server*.log
+            exit 0
           when: always
       - store_artifacts:
           path: artifacts
